# k8s/external-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: docker-registry-creds
  namespace: work-projects-voda-monster
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-cluster-backend
    kind: ClusterSecretStore
  target:
    name: registry-pull-secret
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "registry.goodwin.website": {
                "username": "{{ .username }}",
                "password": "{{ .password }}",
                "auth": "{{ printf "%s:%s" .username .password | b64enc }}"
              }
            }
          }
        htpasswd: "{{ .htpasswd }}"
  data:
  - secretKey: username
    remoteRef:
      key: shared-services/registry
      property: username
  - secretKey: password
    remoteRef:
      key: shared-services/registry
      property: password
  - secretKey: htpasswd
    remoteRef:
      key: shared-services/registry
      property: htpasswd
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: voda-laravel-app-secrets
  namespace: work-projects-voda-monster
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-cluster-backend
    kind: ClusterSecretStore
  target:
    name: voda-laravel-app-secrets # Этот секрет подцепит Deployment через envFrom
  data:
  - secretKey: APP_KEY
    remoteRef:
      key: voda-monster/backend
      property: APP_KEY
  - secretKey: DB_CONNECTION
    remoteRef:
      key: voda-monster/backend
      property: DB_CONNECTION
  - secretKey: DB_DATABASE
    remoteRef:
      key: voda-monster/backend
      property: DB_DATABASE
  - secretKey: DB_HOST
    remoteRef:
      key: voda-monster/backend
      property: DB_HOST
  - secretKey: DB_PASSWORD
    remoteRef:
      key: voda-monster/backend
      property: DB_PASSWORD
  - secretKey: DB_PORT
    remoteRef:
      key: voda-monster/backend
      property: DB_PORT
  - secretKey: DB_USERNAME
    remoteRef:
      key: voda-monster/backend
      property: DB_USERNAME
  - secretKey: GATEWAY_INTERNAL_SECRET
    remoteRef:
      key: voda-monster/backend
      property: GATEWAY_INTERNAL_SECRET
  - secretKey: REDIS_CLIENT
    remoteRef:
      key: voda-monster/backend
      property: REDIS_CLIENT
  - secretKey: REDIS_HOST
    remoteRef:
      key: voda-monster/backend
      property: REDIS_HOST
  - secretKey: REDIS_PASSWORD
    remoteRef:
      key: voda-monster/backend
      property: REDIS_PASSWORD
  - secretKey: REDIS_PORT
    remoteRef:
      key: voda-monster/backend
      property: REDIS_PORT
